name: DRAFT WIP from a SPRINT - PLEASE DO NOT USE THIS TEMPLATE
description:  Use to submit your Python package for pyOpenSci peer review
title: 'Feature: '
labels: ['editor-checks', 'New Submission!']
assignees:
  - placeholder
body:
  - type: input
    id: "Submitting_Author"
    attributes:
      label: Submitting Author
      description: Author Name
      placeholder: github_handle
    validations:
      required: true
  - type: textarea
    id: "maintainer1"
    attributes:
      label: Maintainer 1
      description: GitHub handle for the first mantainer
      placeholder: github_handle1
    validations:
      required: true
  - type: textarea
  id: "maintainer2"
  attributes:
    label: Maintainer 2
    description: GitHub handle for the second mantainer
    placeholder: github_handle2
  validations:
    required: true
  - type: input
    id: "package_name"
    attributes:
      label: Package Name
      description: Package name here
      placeholder: Package name here
    validations:
      required: true
  - type: input
    id: "one_line_desc"
    attributes:
      label: One-Line Description of Package
      description: One-Line Description of Package
      placeholder: description here
    validations:
      required: true
  - type: input
    id: "repository_link"
    attributes:
      label: Repository Link
      description: Link to the package repository
      placeholder: Link to the package repository
    validations:
      required: true
  - type: input
    id: "version_submitted"
    attributes:
      label: Version submitted
      description: Version submitted
      placeholder: Version submitted
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct & Commitment to Maintain Package
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to abide by [pyOpenSci's Code of Conduct][PyOpenSciCodeOfConduct] during the review process and in maintaining my package after should it be accepted.
          required: true
        - label: I have read and will commit to package maintenance after the review as per the [pyOpenSci Policies Guidelines][Commitment].
          required: true
  - type: textarea
    id: "description"
    attributes:
      label: description
      description: Include a brief paragraph describing what your package does
      placeholder: description here
    validations:
      required: true
  - type: checkboxes
    id: ""category"
    attributes:
      label: category
      description: Please one category or categories. Check out our [package scope page][PackageCategories] to learn more about our scope. (If you are unsure of which category you fit, we suggest you make a pre-submission inquiry):
      options:
        - label: Data retrieval
          required: true
        - label: Data extraction
          required: true
        - label: Data processing/munging
          required: true
        - label: Data deposition
          required: true
        - label: Data validation and testing
          required: true
        - label: Data visualization[^1]
          required: true
        - label: Workflow automation
          required: true
        - label: Citation management and bibliometrics
          required: true
        - label: Scientific software wrappers
          required: true
        - label: Database interoperability
  - type: checkboxes
    id: "partnerships"
    attributes:
      label: partnerships
      description: Domain Specific & Community Partnerships 
      options:
        - label: Geospatial
          required: true
        - label: Education
          required: true
        - label: Pangeo
          required: true
  - type: checkboxes
    id: "community_partnerships"
    attributes:
      label: Community partnerships
      description: If your package is associated with an existing community please check below
      options:
        - label: [Pangeo][pangeoWebsite]
          required: true
          - label: My package adheres to the [Pangeo standards listed in the pyOpenSci peer review guidebook][PangeoCollaboration]
            required: true
  - type: textarea
    id: "category_explanation"
    attributes:
      label: Category explanation
      description: For all submissions, explain how the and why the package falls under the categories you indicated above. In your explanation, please address the following points (briefly, 1-2 sentences for each)  
      placeholder: explain here
    validations:
        required: true
  - type: textarea
    id: "target_audience"
    attributes:
      label: audience
      description: Who is the target audience and what are scientific applications of this package?  
      placeholder: audience and applications here
    validations:
      required: true
  - type: textarea
    id: "other_packages"
    attributes:
      label: other packages
      description: Are there other Python packages that accomplish the same thing? If so, how does yours differ?
      placeholder: packages here
    validations:
      required: true
  - type: textarea
    id: "presubmission"
    attributes:
      label: pre-submission enquiry
      description: If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or `@tag` the editor you contacted:
      placeholder: link here
    validations:
      required: true
  - type: checkboxes
    id: "technical_checks"
    attributes:
      label: Technical checks
      description: For details about the pyOpenSci packaging requirements, see our [packaging guide][PackagingGuide]. Confirm each of the following by checking the box. This package:
      options:
        - label: does not violate the Terms of Service of any service it interacts with. 
          required: true
        - label: uses an [OSI approved license][OsiApprovedLicense].
          required: true
        - label: contains a README with instructions for installing the development version. 
          required: true
        - label: includes documentation with examples for all functions.
          required: true
        - label: contains a tutorial with examples of its essential functions and uses.
          required: true
        - label: has a test suite.
          required: true
        - label: has continuous integration setup, such as GitHub Actions CircleCI, and/or others.
          required: true
